### ISSUE TITLE
Error: destroy is not a function

### ISSUE THREAD

**Issue by mbrain-io** [surgeharb/strapi-plugin-graphs-builder#4]
Hi there, when I try to create a graph I get:

```
destroy is not a function
TypeError: destroy is not a function
    at safelyCallDestroy (http://localhost:8000/admin/main.bundle.js:76476:5)
    at commitHookEffectListUnmount (http://localhost:8000/admin/main.bundle.js:76644:11)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (http://localhost:8000/admin/main.bundle.js:78642:11)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (http://localhost:8000/admin/main.bundle.js:78592:5)
    at commitPassiveUnmountEffects_begin (http://localhost:8000/admin/main.bundle.js:78500:11)
    at commitPassiveUnmountEffects (http://localhost:8000/admin/main.bundle.js:78485:3)
    at flushPassiveEffectsImpl (http://localhost:8000/admin/main.bundle.js:80582:3)
    at flushPassiveEffects (http://localhost:8000/admin/main.bundle.js:80528:14)
    at commitRootImpl (http://localhost:8000/admin/main.bundle.js:80479:5)
    at commitRoot (http://localhost:8000/admin/main.bundle.js:80226:5)
```

**Comment by surgeharb** [comment]
Which Strapi version are you using?

**Comment by mbrain-io** [comment]
@surgeharb v4.14.6
